FROM maven:3.9-ibm-semeru-23-jammy as build

ENV HOME=/calc

WORKDIR $HOME

ADD . $HOME

RUN mvn -f $HOME/pom.xml clean package

FROM eclipse-temurin:23.0.1_11-jre-noble

WORKDIR /app

COPY --from=build /calc/target/calculator-1.0.0.jar .

ENV ORIGIN1=localhost:3000
ENV ORIGIN1=localhost:8080

EXPOSE 8080

CMD ["sh", "-c", "java -Dallowed_origin1=$ORIGIN1 -Dallowed_origin2=$ORIGIN2 -Dspring.profiles.active=dev -Xmx256m -jar calculator-1.0.0.jar" ]
