FROM ghcr.io/graalvm/native-image-community:22-muslib as build

RUN microdnf install wget 
RUN microdnf install xz

RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
RUN tar xvf apache-maven-3.9.9-bin.tar.gz

ENV M2_HOME=/app/apache-maven-3.9.9
ENV M2=$M2_HOME/bin
ENV PATH=$M2:$PATH
ENV SRC=/run/media/msa/Dados/tmp/ntd/calc
ENV APPDIR=/app/calc

RUN wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
RUN tar xvf upx-4.2.4-amd64_linux.tar.xz

ENV UPX_HOME=/app/upx-4.2.4-amd64_linux
ENV PATH=$UPX_HOME:$PATH

RUN mkdir -p /app/calc
COPY . /app/calc

RUN cd /app/calc && mvn -Pnative native:compile

RUN upx -7 -k /app/calc/target/app-native-binary
WORKDIR /app

FROM amd64/alpine

WORKDIR /app

COPY --from=build /app/calc/target/app-native-binary .

EXPOSE 8080 

ENTRYPOINT ["/app/app-native-binary"]
